name: Build

on:
  release:
    types: [published]

  push:
    branches: [main]

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: extractions/setup-just@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build without publishing, goreleaser
        uses: goreleaser/goreleaser-action@v3
        if: github.event_name != 'release'
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist

      - name: Build with publishing
        uses: goreleaser/goreleaser-action@v3
        if: github.event_name == 'release'
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
