name: Container

on:
  release:
    types: [published]

  push:
    branches: [main]

env:
  IMAGE_NAME: adztbotv2
  CONTAINER_REGISTRY: ghcr.io

jobs:
  Buildah:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Install QEMU for cross-compilation
        run: | 
          sudo apt update
          sudo apt install qemu-user-static
        
      - name: Format tag and image name
        run: |
          IMAGE_ID=${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

          # Change all uppercase to lowercase and add it to github env
          echo "IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use `latest` tag convention and add it to github env
          [ "$VERSION" == "main" ] && VERSION=latest
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Buildah build
        id: buildah_build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_ID }}
          tags: ${{ env.VERSION }}
          #platforms: linux/amd64, linux/arm64, linux/arm, linux/386, windows/amd64, windows/386, darwin/amd64, darwin/386
          platforms: linux/amd64, linux/arm64, linux/arm, linux/386
          containerfiles: |
            ./Dockerfile
        
      - name: Show buildah_build output
        run: |
          echo "Image: ${{ steps.buildah_build.outputs.image }}"
          echo "Tags: ${{ steps.buildah_build.outputs.tags }}"
          echo "Tagged Image: ${{ steps.buildah_build.outputs.image-with-tag }}"
          
      - name: Check images created in the buildah_build step
        run: buildah images | grep '${{ env.IMAGE_ID }}'

      - name: Check manifest created in the buildah_build step
        run: |
          set -x
          buildah manifest inspect ${{ steps.buildah_build.outputs.image }}:${{ env.VERSION }}

      - name: Push To ${{ env.CONTAINER_REGISTRY }}
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah_build.outputs.image }}
          tags: ${{ steps.buildah_build.outputs.tags }}
          registry: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --disable-content-trust

      - name: Show the push action output
        run: |
          echo "${{ toJSON(steps.push-to-registry.outputs) }}"
