name: Images autoremove

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
          
      - name: Delete old container images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
        run: auth="$GITHUB_REPOSITORY_OWNER:$TOKEN" bash delete_remote_images.sh
