name: Release Binary

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name of the existing release'
        required: true
  release:
    types: [published]

env:
  GO_VERSION: 1.16.x

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Format tag (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          
      - name: Format tag (auto trigger)
        if: github.event_name != 'workflow_dispatch'
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Add VERSION to the action env
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: bash build.sh ${{ env.VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./bin/*.zip

  upload-binary:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ./bin

      - name: Publish binary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.VERSION }} ./bin/*
