name: Release Binary

on:
  release:
    types: [published]

env:
  GO_VERSION: 1.16.x

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Make script executable
        run: chmod +x ./build.sh

      - name: Build
        run: ./build.sh ${{ github.ref }}

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./bin/*.zip

  upload-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: writte
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ./bin

      - name: Publish binary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}}
        run: gh release upload ${GITHUB_REF} ./bin/*
