name: Release Binary

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name of the existing release'
        required: true
  release:
    types: [published]

env:
  GO_VERSION: 1.16.x

jobs:
  build-and-release-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11
          
      - name: Format tag (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          
      - name: Format tag (auto trigger)
        if: github.event_name != 'workflow_dispatch'
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Add VERSION to the action env
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Build and Publish binary
        run: nix-shell --comand="just GH_TOKEN=${{ secrets.GITHUB_TOKEN }} VERSION={{env.VERSION}} release_ci"
